import IconEmail from 'components/icons/IconEmail';

export const prefix = "/admin";
export const menuInfo = [{
    Icon: IconEmail,
    text: "Dashboard",
    to: ["/dashboard"],
    matchingUrl: "/dashboard",
    matchingUrlSidebar: "/dashboard",
    breadCrumb: ["Home", "Dashboard"],
    breadCrumbActiveNum: 1,
    breadCrumbTitle: "Dashboard",
}, {
    Icon: IconEmail,
    text: "Site Settings",
    to: ["/dashboard"],
    matchingUrl: "/site-settings",
    matchingUrlSidebar: "/site-settings",
    breadCrumb: ["Dashboard", "Site Settings"],
    breadCrumbActiveNum: 1,
    breadCrumbTitle: "Site Settings",
}, {
    Icon: IconEmail,
    text: "Application Settings",
    to: ["/dashboard"],
    matchingUrl: "/application-settings",
    matchingUrlSidebar: "/application-settings",
    breadCrumb: ["Dashboard", "Application Settings"],
    breadCrumbActiveNum: 1,
    breadCrumbTitle: "Application Settings",
}, {
    Icon: IconEmail,
    text: "Email Template",
    to: ["/dashboard"],
    matchingUrl: "/email-template/manage",
    matchingUrlSidebar: "/email-template",
    breadCrumb: ["Dashboard", "Manage Email Templates"],
    breadCrumbActiveNum: 1,
    breadCrumbTitle: "Email Templates",
}, {
    Icon: IconEmail,
    text: "Email Template",
    to: ["/dashboard", "/email-template/manage"],
    matchingUrl: "/email-template/edit",
    matchingUrlSidebar: "/email-template",
    breadCrumb: ["Dashboard", "Manage Email Templates", "Edit"],
    breadCrumbActiveNum: 2,
    breadCrumbTitle: "Email Templates",
}, {
    Icon: IconEmail,
    text: "Email Template",
    to: ["/dashboard", "/email-template/manage"],
    matchingUrl: "/email-template/view",
    matchingUrlSidebar: "/email-template",
    breadCrumb: ["Dashboard", "Manage Email Templates", "View"],
    breadCrumbActiveNum: 2,
    breadCrumbTitle: "Email Templates",
}, {
    Icon: IconEmail,
    text: "CMS",
    to: ["/dashboard"],
    matchingUrl: "/cms/manage",
    matchingUrlSidebar: "/cms",
    breadCrumb: ["Dashboard", "Manage CMS"],
    breadCrumbActiveNum: 1,
    breadCrumbTitle: "Manage CMS",
}, {
    Icon: IconEmail,
    text: "CMS",
    to: ["/dashboard", "/cms/manage"],
    matchingUrl: "/cms/edit",
    matchingUrlSidebar: "/cms",
    breadCrumb: ["Dashboard", "Manage CMS", "Edit"],
    breadCrumbActiveNum: 2,
    breadCrumbTitle: "Edit CMS",
}, {
    Icon: IconEmail,
    text: "CMS",
    to: ["/dashboard", "/cms/manage"],
    matchingUrl: "/cms/view",
    matchingUrlSidebar: "/cms",
    breadCrumb: ["Dashboard", "Manage CMS", "View"],
    breadCrumbActiveNum: 2,
    breadCrumbTitle: "Manage CMS Content",
}, {
    Icon: IconEmail,
    text: "Users",
    to: ["/dashboard"],
    matchingUrl: "/users/manage",
    matchingUrlSidebar: "/users",
    breadCrumb: ["Dashboard", "Manage Users"],
    breadCrumbActiveNum: 1,
    breadCrumbTitle: "Manage Users",
}, {
    Icon: IconEmail,
    text: "Users",
    to: ["/dashboard", "/users/manage"],
    matchingUrl: "/users/add",
    matchingUrlSidebar: "/users",
    breadCrumb: ["Dashboard", "Manage Users", "Add"],
    breadCrumbActiveNum: 2,
    breadCrumbTitle: "Manage Users",
}, {
    Icon: IconEmail,
    text: "Users",
    to: ["/dashboard", "/users/manage"],
    matchingUrl: "/users/edit",
    matchingUrlSidebar: "/users",
    breadCrumb: ["Dashboard", "Manage Users", "Edit"],
    breadCrumbActiveNum: 2,
    breadCrumbTitle: "Manage Users",
}, {
    Icon: IconEmail,
    text: "Users",
    to: ["/dashboard", "/users/manage"],
    matchingUrl: "/users/view",
    matchingUrlSidebar: "/users",
    breadCrumb: ["Dashboard", "Manage Users", "View"],
    breadCrumbActiveNum: 2,
    breadCrumbTitle: "Manage Users",
}, {
    Icon: IconEmail,
    text: "Coin Category",
    to: ["/dashboard"],
    matchingUrl: "/coin-category/manage",
    matchingUrlSidebar: "/coin-category",
    breadCrumb: ["Dashboard", "Manage Coin Category"],
    breadCrumbActiveNum: 1,
    breadCrumbTitle: "Manage Coin Category",
}, {
    Icon: IconEmail,
    text: "Coin Category",
    to: ["/dashboard", "/coin-category/manage"],
    matchingUrl: "/coin-category/edit",
    matchingUrlSidebar: "/coin-category",
    breadCrumb: ["Dashboard", "Manage Coin Category", "Edit"],
    breadCrumbActiveNum: 2,
    breadCrumbTitle: "Manage Coin Category",
}, {
    Icon: IconEmail,
    text: "Coins",
    to: ["/dashboard"],
    matchingUrl: "/coins/manage",
    matchingUrlSidebar: "/coins",
    breadCrumb: ["Dashboard", "Manage Coins"],
    breadCrumbActiveNum: 1,
    breadCrumbTitle: "Manage Coins",
}, {
    Icon: IconEmail,
    text: "Coins",
    to: ["/dashboard", "/coins/manage"],
    matchingUrl: "/coins/add",
    matchingUrlSidebar: "/coins",
    breadCrumb: ["Dashboard", "Manage Coins", "Add"],
    breadCrumbActiveNum: 2,
    breadCrumbTitle: "Manage Coins",
}, {
    Icon: IconEmail,
    text: "Coins",
    to: ["/dashboard", "/coins/manage"],
    matchingUrl: "/coins/edit",
    matchingUrlSidebar: "/coins",
    breadCrumb: ["Dashboard", "Manage Coins", "Edit"],
    breadCrumbActiveNum: 2,
    breadCrumbTitle: "Manage Coins",
}, {
    Icon: IconEmail,
    text: "Coins",
    to: ["/dashboard", "/coins/manage"],
    matchingUrl: "/coins/view",
    matchingUrlSidebar: "/coins",
    breadCrumb: ["Dashboard", "Manage Coins", "View"],
    breadCrumbActiveNum: 2,
    breadCrumbTitle: "Manage Coins",
}, {
    Icon: IconEmail,
    text: "Coin News",
    to: ["/dashboard"],
    matchingUrl: "/coin-news/manage",
    matchingUrlSidebar: "/coin-news",
    breadCrumb: ["Dashboard", "Manage Coin News"],
    breadCrumbActiveNum: 1,
    breadCrumbTitle: "Manage Coin News",
}, {
    Icon: IconEmail,
    text: "Coin News",
    to: ["/dashboard", "/coin-news/manage"],
    matchingUrl: "/coin-news/add",
    matchingUrlSidebar: "/coin-news",
    breadCrumb: ["Dashboard", "Manage Coin News", "Add"],
    breadCrumbActiveNum: 2,
    breadCrumbTitle: "Manage Coin News",
}, {
    Icon: IconEmail,
    text: "Coin News",
    to: ["/dashboard", "/coin-news/manage"],
    matchingUrl: "/coin-news/edit",
    matchingUrlSidebar: "/coin-news",
    breadCrumb: ["Dashboard", "Manage Coin News", "Edit"],
    breadCrumbActiveNum: 2,
    breadCrumbTitle: "Manage Coin News",
}, {
    Icon: IconEmail,
    text: "Coin News",
    to: ["/dashboard", "/coin-news/manage"],
    matchingUrl: "/coin-news/view",
    matchingUrlSidebar: "/coin-news",
    breadCrumb: ["Dashboard", "Manage Coin News", "View"],
    breadCrumbActiveNum: 2,
    breadCrumbTitle: "Manage Coin News",
}, {
    Icon: IconEmail,
    text: "Notifications",
    to: ["/dashboard"],
    matchingUrl: "/in-app-notification",
    matchingUrlSidebar: "/in-app-notification",
    breadCrumb: ["Dashboard", "Notifications"],
    breadCrumbActiveNum: 1,
    breadCrumbTitle: "Notifications",
}, {
    Icon: IconEmail,
    text: "Transaction History - Buy BNB",
    to: ["/dashboard"],
    matchingUrl: "/transaction-history/buy-bnb",
    matchingUrlSidebar: "/transaction-history/buy-bnb",
    breadCrumb: ["Dashboard", "Manage Buy BNB Transaction History"],
    breadCrumbActiveNum: 1,
    breadCrumbTitle: "Manage Buy BNB Transaction History",
}, {
    Icon: IconEmail,
    text: "Transaction History - Buy BNB",
    to: ["/dashboard", "/transaction-history/buy-bnb"],
    matchingUrl: "/transaction-history/buy-bnb/details",
    matchingUrlSidebar: "/transaction-history/buy-bnb",
    breadCrumb: ["Dashboard", "Manage Buy BNB Transaction History", "Details"],
    breadCrumbActiveNum: 2,
    breadCrumbTitle: "Manage Buy BNB Transaction History",
}, ];